<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SaleForm.aspx.cs" Inherits="SaleProject.SaleForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>
            Welcome to Sale Service 
        </h2>
        <table class="style1">
            <tr>
                <td class="text-align:right">
                    Enter Name
                </td>
                <td>
                    <asp:TextBox ID="TextBox" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    Address
                </td>
                <td>
                    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    Email ID
                </td>
                <td>
                    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    &nbsp;
                </td>
                <td>
                    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Save" />
                </td>
            </tr>
        </table>
        <p>

            <asp:GridView ID="GridView1" runat="server"
                AllowPaging="true" DataKeyNames="CustomerID,CustomerName"
                    AllowSorting="true" AutoGenerateDeleteButton="true"
                    onrowdeleting="GridView1_RowDeleting" />
            
        </p>
        <p>

            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        </p>
        
    </form>
</body>
</html>
